FAKE_STATUSES = [
    'I hate finals.',
    'Lolll can\'t believe that just happened...',
    'Happy birthday to the best mother ever!',
    'Here goes nothing!',
    'This sucks...',
    'Ugh...so stressed!',
    'College, here I come!',
    'Thanks for all the birthday wishes, everyone!',
]

FAKE_LIKES = [
    'Tennis',
    'Soccer',
    'Shakira',
    'Cristiano Ronaldo',
    'Eminem',
    'Rihanna',
    'Coca-Cola',
    'Vin Diesel',
    'YouTube',
    'Michael Jackson',
    'The Simpsons',
    'Harry Potter',
    'Katy Perry',
    'Justin Bieber',
    'FC Barcelona',
    'Candy Crush Saga',
    'Real Madrid C.F.',
    'Will Smith',
    'Texas HoldEm Poker',
    'Leo Messi',
    'Bob Marley',
    'Taylor Swift',
    'Lady Gaga',
    'Linkin Park',
    'Beyoncé'
]

FAKE_HIGH_SCHOOLS = [
    'Bridgewater Academy',
    'Cheshire High School',
    'Fairview High School',
    'Oakdale Senior High School',
    'School for the Talented and Gifted',
    'BASIS Scottsdale',
    'Gwinnett School of Mathematics, Science and Technology',
    'Thomas Jefferson High School for Science and Technology',
    'BASIS Tucson North',
    'Pine View School',
    'University High School',
    'School of Science and Engineering Magnet',
    'International Academy',
    'Oxford Academy',
    'Biotechnology High School',
    'Stanton College Preparatory School',
    'International Community School',
    'Maine School of Science & Mathematics',
    'Academy of Aerospace and Engineering',
    'Academic Magnet High School',
    'International School',
    'Loveless Academic Magnet Program High School',
    'Design & Architecture Senior High',
    'High Technology High School',
    'Signature School',
    'Whitney High School',
    'Carnegie Vanguard High School',
    'International Studies Charter High School',
    'Pacific Collegiate School',
    'Townsend Harris High School',
    'Staten Island Technical High School',
    'American Indian Public High School',
    'Edgewood Junior-​Senior High School',
    'Lowell High School',
    'Manhattan Bridges High School',
    'Hume-​Fogg Academic High School',
    'Edgemont Junior Senior High School',
    'Walt Whitman High School',
    'Dr. Ronald E. McNair Academic High School',
    'Thomas S. Wootton High School',
    'Rye High School',
    'Jericho High School',
    'George Mason High School',
    'Walnut Hills High School',
    'Poolesville High School',
    'Pittsford Sutherland High School',
    'Harding Charter Preparatory High School',
    'Pittsford Mendon High School',
    'James Madison High School',
    'Eleanor Roosevelt High School',
    'Langley High School',
    'Monta Vista High School',
    'Highland Park High School'        
]

FAKE_COLLEGES = [
    'Brown University',
    'George Washington University',
    'Rice University',
    'University of Miami',
    'University of Wisconsin',
    'Princeton University',
    'Harvard University',
    'Yale University',
    'Columbia University',
    'Stanford University',
    'University of Chicago',
    'Massachusetts Institute of Technology',
    'Duke University',
    'University of Pennsylvania',
    'California Institute of Technology',
    'Dartmouth College',
    'Johns Hopkins University',
    'Northwestern University',
    'Washington University in St. Louis',
    'Cornell University',
    'University of Notre Dame',
    'Vanderbilt University',
    'University of California - Berkeley',
    'Emory University',
    'Georgetown University',
    'University of California - Los Angeles',
    'University of Virginia',
    'Carnegie Mellon University',
    'University of Southern California',
    'Tufts University',
    'Wake Forest University',
    'University of Michigan - Ann Arbor',
    'University of North Carolina - Chapel Hill',
    'Boston College',
    'New York University',
    'College of William and Mary',
    'University of Rochster',
    'Brandeis University',
    'Georgia Institute of Technology',
    'University of California - San Diego',
    'University of Central Florida',
    'University of Texas - Austin',
    'Auburn University',
    'University of Alabama',
    'Texas A&M University — College Station',
    'Ohio State University — Columbus',
    'Pennsylvania State University — University Park',
    'Arizona State University — Tempe',
    'Michigan State University'
    'University of Florida',
]

FAKE_DEGREES = [
    'Art History',
    'Biology',
    'Computer Science',
    'English',
    'History',
    'Human Biology',
    'Mathematics',
    'Mechanical Engineering',
    'Accounting',
    'Art and Design',
    'Architecture',
    'Business',
    'Civil Engineering',
    'Communications Studies',
    'Criminal Justice',
    'Education',
    'Economics',
    'English',
    'Electrical Engineering',
    'Finance',
    'Graphic Design',
    'Interior Design',
    'Journalism',
    'Applied Mathematics',
    'Marketing',
    'Nutrition',
    'Political Science',
    'International Relations',
    'Psychology',
    'Religious Studies',
    'Sports Management'
]
